---
language: node_js
node_js:
  - "10"

sudo: false
addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm run install
script:
  - npm test
